version: "3"

services:
  reverse-proxy:
    image: traefik:v2.5.3
    restart: unless-stopped
    # command: --providers.docker
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./certs:/certs 
  origin:
    image: python
    entrypoint: bash -c "mkdir /app && cd /app && echo 'It works!' > index.html && python -m http.server 80"

    labels:
      # Enable this container to be mapped by traefik
      - "traefik.enable=true"
      # URL to reach this container
      - "traefik.http.routers.origin.rule=Host(`origin.docker.localhost`)"
      # If port is different than 80, use the following service:
      - "traefik.http.services.origin.loadbalancer.server.port=80"
      # Activation of TLS
      - "traefik.http.routers.origin.tls=true"
  






