version: "3"

services:

  reverse-proxy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./www.lzytest.tech.crt:/etc/caddy/server.crt
      - ./www.lzytest.tech.key:/etc/caddy/server.key

  origin:
    image: python
    entrypoint: bash -c "mkdir /app && cd /app && echo 'It works!' > index.html && python -m http.server 80"
