version: "3"

services:
  reverse-proxy:
    image: traefik:v2.5.3
    command: --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
  origin:
    image: python
    entrypoint: bash -c "mkdir /app && cd /app && echo 'It works!' > index.html && python -m http.server 80"
    labels:
      - "traefik.http.routers.origin.rule=Host(`origin.docker.localhost`)"
      - "traefik.http.services.origin.loadbalancer.server.port=80"




