version: "3"

services:

  reverse-proxy:
    image: nginx:1.21.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80

  origin:
    image: httpd
