version: "3"

services:

  reverse-proxy:
    image: haproxy:2.5-dev10
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www.lzytest.tech.pem:/usr/local/etc/haproxy/site.pem
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg    
    depends_on:
      - origin

  origin:
    image: caddy:2.4.5
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./index.html:/usr/share/caddy/index.html